### ISSUE TITLE
variance_est and varpoord

### ISSUE THREAD

**Issue by DjalmaPessoa** [CSBLatvia/vardpoor#1]
I've been using the library vardpoor jointly with the library survey. When estimating variances using the ultimate cluster method I found different results by the two libraries:

```
library(vardpoor)
set.seed(1)
Ys <- rchisq(10, 3)
w <- rep(2, 10)
PSU <- 1:length(Ys)
H <- rep("Strata_1", 10)
variance_est(Y=Ys, H=H, PSU=PSU, w_final=w)

# result: 73.26389

# directly using formulas: one stratum with 10 clusters

# total estimator
Yhat_CP<- sum(Ys*w)

# variance estimator:
Yhat_h<- sum(Ys*w)

(10/9)*sum((Ys*w-Yhat_h/10)^2)

# result: 146.5278


## using library survey
library(survey)
data<- data.frame(Y=Ys, H=H, w=w, PSU=PSU)
des<- svydesign(id=~PSU, strata=~H, weights =~w, data= data)

vcov(svytotal(~Y, des))

# result: 146.5278
```

I was not able to figure it out the reason for the difference.

Also, in trying to reproduce the examples of the function varpoord I found different values for the same estimates:

```
library(vardpoor)
data(eusilc)
dataset <- data.frame(1:nrow(eusilc),eusilc)
colnames(dataset)[1] <- "IDd"
dataset1 <- dataset[1:1000,]
```

 Example 2:  arpt for domains

```
aa1 <-varpoord(Y = "eqIncome", w_final = "rb050",
  Y_thres = NULL, wght_thres = NULL,
  ID_household = "db030", id = "IDd",
  H = "db040", PSU = "rb030", N_h = NULL,
  sort = NULL, Dom = "db040",
  gender = NULL, X = NULL,
  X_ID_household = NULL, g = NULL,
  datasetX = NULL,
  q = rep(1, if (is.null(datasetX))
    nrow(as.data.frame(H)) else nrow(datasetX)),
  dataset =  dataset1, percentage=60, order_quant=50,
  alpha = 20, confidence = .95, outp_lin = FALSE,
  outp_res = FALSE, several.ok=FALSE, type="linarpt")

# result 1
as.data.frame(as.data.frame(aa1$all_result))[,c("type","db040","value", "se")]

# example 3: all_choices for domains

aa2 <- varpoord(Y = "eqIncome", w_final = "rb050",
  Y_thres = NULL, wght_thres = NULL,
  ID_household = "db030", id = "IDd",
  H = "db040", PSU = "rb030", N_h = NULL,
  sort = NULL, Dom = "db040",
  gender = NULL, X = NULL,
  X_ID_household = NULL, g = NULL,
  datasetX = NULL,
  q = rep(1, if (is.null(datasetX))
    nrow(as.data.frame(H)) else nrow(datasetX)),
  dataset =  dataset, percentage=60, order_quant=50,
  alpha = 20, confidence = .95, outp_lin = TRUE,
  outp_res = TRUE, several.ok=FALSE, type="all_choices")

# result 2
subset(as.data.frame(aa2$all_result)[,c("type","db040","value", "se")],type=="ARPT")
```

 why the results 1 and 2 are not the same?

Thank you for any help on that.

Djalma Pessoa
pessoad@gmail.com

**Comment by JBreidaks** [comment]
Function `variance_est(Y=Ys, H=H, PSU=PSU, w_final=w)` by default is used finite population correction argument `fh_zero=FALSE`. If you do not want use finite population correction, then you must define argument `fh_zero=TRUE`. 

```
library(vardpoor)
set.seed(1)
Ys <- rchisq(10, 3)
w <- rep(2, 10)
PSU <- 1:length(Ys)
H <- rep("Strata_1", 10)`
```

by default

```
variance_est(Y=Ys, H=H, PSU=PSU, w_final=w)
```

result: 73.26389

without using `fh_zero`

```
variance_est(Y=Ys, H=H, PSU=PSU, w_final=w, fh_zero=FALSE)
```

result: 73.26389

with using `fh_zero`

```
variance_est(Y=Ys, H=H, PSU=PSU, w_final=w, fh_zero=TRUE)
```

result:  146.5278

```
library(survey)
data<- data.frame(Y=Ys, H=H, w=w, PSU=PSU)
des<- svydesign(id=~PSU, strata=~H, weights =~w, data= data)

vcov(svytotal(~Y, des))
```

result:   146.5278

About second problem there must use the same dataset, because in example 2 is used `dataset1`, but in example 3 is used dataset. And example 3 `several.ok` must be `TRUE`.

**Comment by ajdamico** [comment]
hi juris and martins, in the second reference of `?variance_est` --

```
Yves G. Berger, Tim Goedeme, Guillame Osier (2013). 
Handbook on standard error estimation and other related sampling issues in EU-SILC, URL 
http://www.cros-portal.eu/content/handbook-standard-error-estimation-and-other-related-sampling-issues-ver-29072013
```

-- that page takes you to [a zipped file](http://www.cros-portal.eu/sites/default/files//Handbook%20on%20Standard%20error%20estimation%20and%20other%20related%20sampling%20issues%20in%20EU-SILC%20%28Berger%2C%20Goedem%C3%A9%2C%20Osier%29.zip) that users can view the `ultimate cluster method` in the document `Chapter 1 (G. Osier) - Standard error estimation for cross-sectional measures.doc` within that zipped file.

![forumla 20](https://cloud.githubusercontent.com/assets/216807/9699840/067ddb84-53be-11e5-8938-071e70be734b.png)

this formula does not mention using `fpc` as a part of the calculation.  we are confused why this was chosen as the default for the `ultimate cluster method` as opposed to simply a user option?  could you elaborate on why that decision was made?

the main assumption of the method is that the `PSUs` are selected with replacement, so no population correction is needed.  defaulting to `fh_zero=TRUE` would arrive at a more conservative estimate of the variance.

thanks very much for your time!  and our apologies if we're overlooking something else here (this stuff gets confusing sometimes)   ;)

-djalma and anthony

**Comment by JBreidaks** [comment]
More about fpc can read in Morris H. Hansen, William N. Hurwitz, William G. Madow, (1953), Sample survey methods and theory Volume I Methods and applications, 257-258, Wiley.

Guillaume Osier and Emilio Di Meglio paper "The linearisation approach implemented by Eurostat for
the first wave of EU-SILC: what could be done from the second onwards?" in  2012:

![image](https://cloud.githubusercontent.com/assets/9083064/9710546/5dd89a40-5544-11e5-9d3d-199e0fb59757.png)

 (20) usually underestimates the unknown variance. In many cases, however, the underestimation is negligible, particularly when the first-stage sampling fraction is small. If not, the formula can still be adjusted using finite population correction factors:

![image](https://cloud.githubusercontent.com/assets/9083064/9710481/9c08f2fc-5543-11e5-9b71-23ba4b69ea74.png)

However, the finite population correction factor ![image](https://cloud.githubusercontent.com/assets/9083064/9710511/0864f02c-5544-11e5-9542-eea1cf491e56.png) may be difficult to compute for all strata. If so, (20) is preferable. Since ![image](https://cloud.githubusercontent.com/assets/9083064/9710516/1247576a-5544-11e5-82e6-fd6842e8b307.png) (20) is also a more conservative estimator.

**Comment by djhurio** [comment]
We have set `fh_zero = FALSE` by default because we usually apply the finite population correction during the variance estimation.
